Cannonical K Means


In [3]:
from sklearn.datasets import make_blobs

#centers and k are same
#cluster_assignments is your potential solution
X, cluster_assignments = make_blobs(n_samples=200, centers=4, cluster_std=0.60, random_state=0)
X


array([[ 2.23421043e+00,  1.69349520e+00],
       [-1.05510724e+00,  2.63803080e+00],
       [ 1.08272576e+00,  4.06271877e+00],
       [-2.60159431e+00,  7.22195591e+00],
       [ 1.60841463e+00,  4.01800537e-01],
       [ 9.82570091e-01,  5.37530962e+00],
       [-1.71343572e+00,  2.97632236e+00],
       [ 4.43598630e-01,  3.11530945e+00],
       [ 1.71444449e+00,  5.02521524e+00],
       [ 1.41372442e+00,  4.38117707e+00],
       [ 5.95676822e-01,  4.08614263e+00],
       [ 2.43040639e+00, -6.35709334e-02],
       [-2.10047101e+00,  2.71029320e+00],
       [-2.45138222e+00,  2.95583946e+00],
       [ 3.20903274e+00,  1.78597253e+00],
       [ 1.86922139e+00,  5.44132083e+00],
       [-1.46707190e+00,  7.92948233e+00],
       [-1.25766504e+00,  7.93201692e+00],
       [-1.40889590e+00,  7.15865322e+00],
       [ 1.53853211e+00,  2.04370263e+00],
       [-1.68001841e+00,  7.34766422e+00],
       [-8.35505074e-01,  3.56565342e+00],
       [ 1.84287117e+00,  7.26928839e-02],
       [-1.

In [4]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn import cluster
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
plt.style.use('dark_background')
from cluster import cluster

class KMeans(cluster):
    
    def __init__(self, K=5, max_iterations=100):
        self.K = K
        self.max_iterations = max_iterations
    
    def create_random_centroids(self, X, num_columns, num_rows):

        centroids = np.zeros((self.K, num_columns))
        for k in range(self.K):
            centroid = X[np.random.choice(range(num_rows))]
            centroids[k] = centroid
        return centroids
    
    def create_cluster(self, X, centroids):
        clusters = [[] for _ in range(self.K)]
        for point_idx, point in enumerate(X):
            closest_centroid = np.argmin(
                np.sqrt(np.sum((point-centroids)**2, axis=1))
            )#Calculate Eucledian Distance
            clusters[closest_centroid].append(point_idx)
        return clusters 
    
    def new_centroids(self, cluster, X, num_columns):
        centroids = np.zeros((self.K, num_columns))
        for idx, cluster in enumerate(cluster):
            new_centroid = np.mean(X[cluster], axis=0)
            centroids[idx] = new_centroid
        return centroids
    
    def identify_cluster(self, clusters, X, num_rows):
        y_pred = np.zeros(num_rows)
        for cluster_idx, cluster in enumerate(clusters):
            for sample_idx in cluster:
                y_pred[sample_idx] = cluster_idx
        return y_pred
     
    def fit(self, X):
        num_rows, num_columns = X.shape
        centroids = self.create_random_centroids(X, num_columns, num_rows)
        for _ in range(self.max_iterations):
            clusters = self.create_cluster(X, centroids)
            prev_centroids = centroids
            centroids = self.new_centroids(clusters, X, num_columns)
            difference = centroids - prev_centroids
            if not difference.any():
                break
        y_pred = self.identify_cluster(clusters, X, num_rows) # predict function
        
        return y_pred, centroids

In [7]:
kmeans = KMeans(K=4, max_iterations=100)
y_pred = kmeans.fit(X)
y_pred

(array([1., 0., 0., 3., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 3.,
        3., 2., 1., 3., 0., 1., 0., 1., 1., 2., 1., 1., 0., 2., 0., 0., 1.,
        0., 0., 0., 0., 0., 3., 2., 3., 2., 0., 1., 0., 0., 3., 2., 0., 3.,
        0., 0., 3., 1., 2., 0., 1., 2., 1., 3., 0., 1., 0., 3., 0., 1., 3.,
        0., 0., 1., 1., 0., 0., 0., 2., 0., 0., 1., 1., 3., 0., 1., 0., 0.,
        0., 0., 1., 0., 0., 3., 3., 3., 0., 0., 1., 0., 2., 1., 0., 3., 1.,
        1., 2., 3., 0., 0., 1., 1., 0., 3., 0., 0., 1., 1., 0., 0., 0., 2.,
        0., 3., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 3., 3., 0.,
        3., 3., 1., 3., 1., 0., 1., 1., 0., 1., 0., 1., 0., 3., 3., 3., 0.,
        0., 1., 0., 3., 0., 3., 1., 3., 1., 1., 0., 0., 3., 0., 1., 1., 0.,
        1., 0., 0., 3., 3., 3., 0., 2., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
        2., 0., 3., 1., 1., 0., 2., 0., 0., 0., 0., 2., 1.]),
 array([[-0.42159285,  3.60192217],
        [ 2.07765826,  1.06995698],
        [-1.02067702,  6.91712

In [8]:
np.unique(y_pred[0], return_counts=True)

(array([0., 1., 2., 3.]), array([96, 52, 16, 36]))

Extend K Means

In [9]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt
from sklearn import cluster
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.datasets import make_blobs
plt.style.use('dark_background')
from cluster import cluster

class KMeans(cluster):
    
    def __init__(self, K=5, max_iterations=100, balanced = False):
        self.K = K
        self.max_iterations = max_iterations
        self.balanced = balanced
    
    def create_random_centroids(self, X, num_columns, num_rows):

        centroids = np.zeros((self.K, num_columns))
        for k in range(self.K):
            centroid = X[np.random.choice(range(num_rows))]
            centroids[k] = centroid
        return centroids
    
    def create_cluster(self, X, centroids):
        
        if self.balanced:
            num_points = X.shape[0]
            distances = np.sqrt(((X - centroids[:, np.newaxis])**2).sum(axis=2))
            closest_centroids = np.argmin(distances, axis=0)
            order = np.argsort(distances[closest_centroids, range(num_points)])
            clusters = [[] for _ in range(self.K)]
            for i, idx in enumerate(order):
                cluster_idx = i % self.K
                clusters[cluster_idx].append(idx)
        else:
            clusters = [[] for _ in range(self.K)]
            for point_idx, point in enumerate(X):
                closest_centroid = np.argmin(
                    np.sqrt(np.sum((point-centroids)**2, axis=1))
                )#Calculate Eucledian Distance
                clusters[closest_centroid].append(point_idx)
        
        return clusters
    
    def new_centroids(self, cluster, X, num_columns):
        centroids = np.zeros((self.K, num_columns))
        for idx, cluster in enumerate(cluster):
            new_centroid = np.mean(X[cluster], axis=0)
            centroids[idx] = new_centroid
        return centroids
    
    def identify_cluster(self, clusters, X, num_rows):
        y_pred = np.zeros(num_rows)
        for cluster_idx, cluster in enumerate(clusters):
            for sample_idx in cluster:
                y_pred[sample_idx] = cluster_idx
        return y_pred
     
    def fit(self, X):
        num_rows, num_columns = X.shape
        centroids = self.create_random_centroids(X, num_columns, num_rows)
        for _ in range(self.max_iterations):
            clusters = self.create_cluster(X, centroids)
            prev_centroids = centroids
            centroids = self.new_centroids(clusters, X, num_columns)
            difference = centroids - prev_centroids
            if not difference.any():
                break
        y_pred = self.identify_cluster(clusters, X, num_rows) # predict function
        
        return y_pred, centroids

In [10]:
kmeans = KMeans(K=4, max_iterations=100, balanced = True)
y_pred = kmeans.fit(X)
y_pred

(array([2., 0., 1., 3., 2., 1., 1., 0., 0., 2., 2., 2., 0., 3., 1., 3., 2.,
        2., 2., 3., 2., 2., 0., 3., 1., 3., 3., 0., 2., 3., 3., 3., 3., 0.,
        2., 3., 0., 3., 1., 2., 2., 3., 3., 3., 2., 0., 3., 2., 2., 2., 0.,
        1., 2., 0., 2., 1., 2., 2., 1., 0., 3., 2., 2., 0., 2., 1., 2., 3.,
        2., 3., 3., 1., 1., 1., 2., 0., 2., 3., 3., 3., 2., 0., 1., 0., 0.,
        0., 1., 1., 0., 0., 0., 2., 1., 2., 0., 0., 3., 0., 1., 3., 0., 3.,
        1., 2., 1., 2., 3., 3., 0., 3., 3., 1., 1., 3., 0., 3., 3., 1., 0.,
        0., 1., 3., 3., 3., 1., 1., 2., 2., 1., 3., 2., 2., 0., 3., 3., 0.,
        1., 2., 2., 1., 1., 3., 1., 2., 1., 3., 1., 0., 3., 1., 1., 1., 3.,
        1., 1., 2., 0., 2., 2., 1., 0., 3., 1., 2., 3., 2., 1., 3., 0., 2.,
        0., 0., 1., 0., 0., 3., 2., 1., 0., 2., 1., 2., 0., 3., 0., 0., 0.,
        1., 1., 0., 1., 1., 1., 0., 0., 1., 0., 0., 3., 0.]),
 array([[-0.09774864,  3.9776478 ],
        [ 0.19385138,  3.75657555],
        [-0.24275122,  4.25483

In [11]:
np.unique(y_pred[0], return_counts=True)

(array([0., 1., 2., 3.]), array([50, 50, 50, 50]))

Cannonical K means implementation on weather data


In [12]:
import pandas as pd

df= pd.read_csv('historical-weather.csv')
df

rowID     hpwren_timestamp  air_pressure  air_temp  \
0            0  2011-09-10 00:00:49         912.3     64.76   
1          100  2011-09-10 01:40:49         911.8     62.96   
2          200  2011-09-10 03:20:49         911.4     68.00   
3          300  2011-09-10 05:00:49         911.4     64.22   
4          400  2011-09-10 06:40:49         912.2     52.70   
...        ...                  ...           ...       ...   
15868  1586800  2014-09-10 16:23:29         914.3     77.18   
15869  1586900  2014-09-10 18:03:29         914.4     77.00   
15870  1587000  2014-09-10 19:43:29         914.9     75.92   
15871  1587100  2014-09-10 21:23:29         915.7     75.38   
15872  1587200  2014-09-10 23:03:29         915.9     75.74   

       avg_wind_direction  avg_wind_speed  max_wind_direction  max_wind_speed  \
0                    97.0             1.2               106.0             1.6   
1                    95.0             2.3               106.0             2.5   
2                    53.0             0.3                69.0             0.5   
3                   191.0             2.8               197.0             2.9   
4                   181.0             1.5               191.0             2.0   
...                   ...             ...                 ...             ...   
15868               225.0             5.2               238.0             6.0   
15869               190.0             1.5               196.0             1.7   
15870               344.0             0.4               352.0             0.6   
15871                13.0             1.5                24.0             1.7   
15872               335.0             0.9               348.0             1.1   

       min_wind_direction  min_wind_speed  rain_accumulation  rain_duration  \
0                    85.0             1.0                NaN            NaN   
1                    88.0             1.9                0.0            0.0   
2                    19.0             0.2                0.0            0.0   
3                   185.0             2.6                0.0            0.0   
4                   164.0             1.2                0.0            0.0   
...                   ...             ...                ...            ...   
15868               214.0             4.4                0.0            0.0   
15869               185.0             1.4                0.0            0.0   
15870               336.0             0.3                0.0            0.0   
15871                 4.0             1.2                0.0            0.0   
15872               322.0             0.7                0.0            0.0   

       relative_humidity  
0                   60.5  
1                   63.9  
2                   33.4  
3                   58.2  
4                   89.8  
...                  ...  
15868               43.2  
15869               42.8  
15870               43.9  
15871               46.7  
15872               47.8  

[15873 rows x 13 columns]

In [13]:
numerical_df = df.iloc[:,2:]
numerical_df

air_pressure  air_temp  avg_wind_direction  avg_wind_speed  \
0             912.3     64.76                97.0             1.2   
1             911.8     62.96                95.0             2.3   
2             911.4     68.00                53.0             0.3   
3             911.4     64.22               191.0             2.8   
4             912.2     52.70               181.0             1.5   
...             ...       ...                 ...             ...   
15868         914.3     77.18               225.0             5.2   
15869         914.4     77.00               190.0             1.5   
15870         914.9     75.92               344.0             0.4   
15871         915.7     75.38                13.0             1.5   
15872         915.9     75.74               335.0             0.9   

       max_wind_direction  max_wind_speed  min_wind_direction  min_wind_speed  \
0                   106.0             1.6                85.0             1.0   
1                   106.0             2.5                88.0             1.9   
2                    69.0             0.5                19.0             0.2   
3                   197.0             2.9               185.0             2.6   
4                   191.0             2.0               164.0             1.2   
...                   ...             ...                 ...             ...   
15868               238.0             6.0               214.0             4.4   
15869               196.0             1.7               185.0             1.4   
15870               352.0             0.6               336.0             0.3   
15871                24.0             1.7                 4.0             1.2   
15872               348.0             1.1               322.0             0.7   

       rain_accumulation  rain_duration  relative_humidity  
0                    NaN            NaN               60.5  
1                    0.0            0.0               63.9  
2                    0.0            0.0               33.4  
3                    0.0            0.0               58.2  
4                    0.0            0.0               89.8  
...                  ...            ...                ...  
15868                0.0            0.0               43.2  
15869                0.0            0.0               42.8  
15870                0.0            0.0               43.9  
15871                0.0            0.0               46.7  
15872                0.0            0.0               47.8  

[15873 rows x 11 columns]